# Generated by Django 3.2.6 on 2021-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210828_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Admin User'), ('PU', 'Partner User'), ('MAU', 'Marketing Admin User'), ('MU', 'Marketer User')], max_length=100, null=True),
        ),
    ]
