# Generated by Django 3.2.6 on 2021-08-23 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Generated'), (2, 'Approved'), (3, 'Cancelled')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commissions',
                'verbose_name_plural': 'Commissionss',
                'db_table': 'commission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommissionSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Percent', 'Percent')], max_length=100, null=True)),
                ('figure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commission Setup',
                'verbose_name_plural': 'Commission Setups',
                'db_table': 'commission_setup',
                'managed': True,
            },
        ),
    ]
