# Generated by Django 3.2.6 on 2021-08-23 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Generated'), (2, 'Admitted'), (3, 'Commissioned'), (4, 'Approved'), (5, 'Cancelled')], null=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=100)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partner_bio',
                'managed': True,
            },
        ),
    ]
