# Generated by Django 3.2.6 on 2021-09-17 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0003_coupon_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Generated'), (2, 'Admitted'), (3, 'Commissioned'), (4, 'Approved'), (5, 'Cancelled')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupon_status_coupon', to='partner.coupon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupon_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Status',
                'verbose_name_plural': 'Coupon Statuses',
                'db_table': 'coupon_status',
                'managed': True,
            },
        ),
    ]
