# Generated by Django 3.2.6 on 2021-09-13 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_question_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
