# Generated by Django 3.2.6 on 2021-09-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedbackresponse_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='branch_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
