# Generated by Django 3.2.6 on 2021-09-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210823_2224'),
        ('feedback', '0007_feedbackresponse_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_feedback_response', to='patient.attendance'),
        ),
    ]
