# Generated by Django 3.2.6 on 2021-08-23 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engaged_with', models.CharField(blank=True, choices=[('I', 'Individual'), ('C', 'Company')], max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
                'db_table': 'engagement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Joint', 'Joint'), ('Group', 'Group')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_time', models.TimeField(blank=True, null=True)),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('reschedule_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments_planner', to='schedule.Comment')),
            ],
            options={
                'verbose_name': 'Planner',
                'verbose_name_plural': 'Planners',
                'db_table': 'planner',
                'managed': True,
            },
        ),
    ]
