# Generated by Django 3.2.6 on 2021-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210904_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='activity_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='planner',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
