# Generated by Django 3.2.6 on 2021-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
