# Generated by Django 3.2.6 on 2021-09-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210823_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_first',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
